# Accelerometro (m/s²)
float32 accel_x 
float32 accel_y #Rileva accelerazione avanti/indietro → movimento lineare
float32 accel_z #Rileva gravità/salti → stabilità verticale

# Giroscopio (rad/s)
float32 gyro_x #Rotazioni su altri assi → movimenti complessi
float32 gyro_y #Rotazioni su altri assi → movimenti complessi 
float32 gyro_z #Rotazioni su altri assi → movimenti complessi

# Angoli orientamento (radianti)
float32 angle_x  # Roll (inclinazione laterale del robot)
float32 angle_y  # Pitch (inclinazione avanti/indietro del robot)
